title: IPIN LABS API Reference Page
description: Ipin Labs API Reference Page
theme: just-the-docs

url: https://just-the-docs.github.io

back_to_top: true
back_to_top_text: "Back to top"

callouts: 
  warning: 
    title: Warning
    color: red
  important: 
    title: Important
    color: blue
  highlight: 
    title: Highlight
    color: yellow
  note: 
    title: Note
    color: purple
  new: 
    title: New
    color: green
  code:
    title: Code
    color: grey-dk
  post:
    title: Post
    color: post
  get:
    title: Get
    color: get