title: IpinLabs API Documents Page
description: IpinLabs API Documents Page
theme: just-the-docs

url: https://just-the-docs.github.io

callouts: 
  warning: 
    title: Warning
    color: red
  important: 
    title: Important
    color: blue
  highlight: 
    title: Highlight
    color: yellow
  note: 
    title: Note
    color: purple
  new: 
    title: New
    color: green
  code:
    title: Code
    color: grey-dk